version: '3.9'

services:

  nodeserver:
    build: 
      context: ./node
      dockerfile: Dockerfile
    image: fullcycle/node:latest
    container_name: node
    networks:
      - node-nginx-network
    volumes:
      - ./node:/usr/src/app
    entrypoint: sh -c "npm install npm@latest && node ./index.js"
    tty: true
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
      interval: 5s
      timeout: 10s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
  
  nginxserver:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: fullcycle/nginx:latest
    container_name: nginx
    networks: 
      - node-nginx-network
    ports: 
      - "8080:80"
    depends_on:
      nodeserver:
        condition: service_healthy

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-nginx-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3


networks: 
  node-nginx-network:
    driver: bridge      
