# base
FROM node:15 as builder
WORKDIR /usr/src/app
COPY . .

# for production
FROM node:15-alpine3.13
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/ .

EXPOSE 3000

ENTRYPOINT ["node","./index.js"]